version: "3.9"
name: blog-api
services:
  app:
    build: .
    ports:
      - 80:80
    environment:
      ConnectionStrings__BlogContext: Server=db;Port=5432;Database=BlogDb;User Id=postgres;Password=${db_password};
      Auth__Username: ${admin_username} 
      Auth__Password: ${admin_password}
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${db_password}
volumes:
  db-vol: